const words = [
"apple", "banana", "grape", "orange", "mango",
            "strawberry", "blueberry", "raspberry", "peach", "pear",
            "plum", "kiwi", "pineapple", "coconut", "watermelon",
            "apricot", "blackberry", "fig", "pomegranate", "lemon",
            "lime", "cherry", "tangerine", "papaya", "passionfruit",
            "date", "nectarine", "clementine", "guava", "dragonfruit",
            "lychee", "jackfruit", "starfruit", "persimmon", "rhubarb",
            "cranberry", "currant", "honeydew", "cantaloupe", "blood orange",
            "raspberry", "tangerine", "soursop", "plantain", "bitter melon",
            "mandarin", "pawpaw", "salak", "longan", "marang",
            "blackcurrant", "redcurrant", "youngberry", "boysenberry", "barberry",
            "kumquat", "bitter orange", "sweet lime", "citrus", "satsuma",
            "chokeberry", "olive", "serviceberry", "bilberry", "barberry",
            "mulberry", "camu camu", "miracle fruit", "jambolan", "salal",
            "yuzu", "calamondin", "jackfruit", "bignay", "feijoa",
            "rambutan", "sapote", "curry leaf", "mangosteen", "soursop",
            "fuyu persimmon", "cempedak", "ziziphus", "cobnut", "hazelnut",
            "macadamia", "pistachio", "chestnut", "brazil nut", "marzipan",
            "mangaba", "nashi pear", "caco", "sapodilla", "cocona",
            "cherimoya", "yangmei", "loquat", "bitter orange", "black sapote",
            "buriti", "coconut", "golden apple", "jungle banana", "monstera",
            "pepino", "jostaberry", "noni", "red banana", "wineberry",
            "salak", "lulo", "genip", "cocorite", "finger lime",
            "black mulberry", "bush tomato", "catuaba", "jicama", "chayote",
            "breadfruit", "cabbage palm", "marang", "kwini", "kepel",
            "white sapote", "koko", "pluot", "nectaplum", "plumcot",
            "apricot", "pear", "orange", "mandarin", "lemon",
            "lime", "tangerine", "grapefruit", "pomelo", "peach",
            "nectarine", "cherry", "date", "fig", "pomegranate",
            "persimmon", "kiwi", "passionfruit", "starfruit", "jackfruit",
            "rambutan", "dragonfruit", "salak", "mangosteen", "custard apple",
            "cacao", "carambola", "kiwifruit", "lychee", "tamarillo",
            "calamansi", "chikoo", "duku", "langsat", "sugar apple",
            "jambu", "pummelo", "physalis", "honeycrisp", "sour cherry",
            "barbadine", "tamarind", "mamey sapote", "jungle jalapeño", "camito",
            "cucumber", "zucchini", "pumpkin", "squash", "sunchoke",
            "artichoke", "asparagus", "radish", "beet", "carrot",
            "turnip", "parsnip", "rutabaga", "celery", "kohlrabi",
            "broccoli", "cauliflower", "brussels sprouts", "cabbage", "green bean",
            "spinach", "swiss chard", "kale", "collard greens", "mustard greens",
            "bok choy", "arugula", "endive", "escarole", "lettuce",
            "watercress", "pea", "bean", "lentil", "chickpea",
            "quinoa", "amaranth", "buckwheat", "rice", "oat",
            "barley", "wheat", "millet", "sorghum", "teff",
            "corn", "potato", "sweet potato", "yam", "cassava",
            "ginger", "turmeric", "garlic", "onion", "leek",
            "shallot", "chive", "scallion", "cilantro", "parsley",
            "basil", "oregano", "thyme", "rosemary", "sage",
            "peppermint", "spearmint", "tarragon", "fennel", "cumin",
            "coriander", "nutmeg", "cardamom", "clove", "anise",
            "vanilla", "cinnamon", "allspice", "mace", "mustard",
            "horseradish", "wasabi", "black pepper", "white pepper", "paprika",
            "chili", "cayenne", "jalapeño", "serrano", "habanero",
            "bell pepper", "banana pepper", "poblano", "chipotle", "green chili",
            "tomatillo", "cabbage", "eggplant", "zucchini", "bell pepper",
            "hot pepper", "sweet pepper", "tomato", "cucumber", "pumpkin",
            "pineapple", "kiwifruit", "nectarine", "pluot", "plumcot",
            "watermelon", "canteloupe", "honeydew", "starfruit", "mangosteen",
            "apricot", "pear", "grapefruit", "lime", "lemon",
            "orange", "blood orange", "tangerine", "satsuma", "clementine",
            "mandarin", "kumquat", "pummelo", "yuzu", "citron",
            "dragonfruit", "rambutan", "passionfruit", "jackfruit", "black sapote",
            "salak", "cempedak", "sapodilla", "longan", "soursop",
            "mamey", "chempedak", "white sapote", "fig", "cherimoya",
            "bilimbi", "rose apple", "carambola", "durian", "bignay",
            "cacao", "bilberry", "cloudberry", "gooseberry", "serviceberry",
            "raspberry", "blackberry", "blueberry", "youngberry", "boysenberry",
            "currant", "grape", "huckleberry", "cranberry", "marionberry",
            "dewberry", "chokecherry", "cherry", "date", "jackfruit",
            "jostaberry", "salmonberry", "wild berry", "bitter melon", "cucamelon",
            "cattley guava", "genip", "bush tomato", "beach strawberry", "strawberry guava",
            "sea grape", "winged bean", "winged bean", "pepino", "rambai",
            "salak", "dragon fruit", "soursop", "cherry", "loquat",
            "monk fruit", "seabuckthorn", "grumichama", "mamoncillo", "kanikou",
            "chikoo", "nashi pear", "jungle jalapeño", "duku", "mangaba",
            "fig", "grapefruit", "blood orange", "tangerine", "blood orange",
            "kiwi", "avocado", "mango", "banana", "lime",
            "lemon", "watermelon", "coconut", "pineapple", "pomegranate",
            "passionfruit", "apricot", "peach", "plum", "soursop",
            "longan", "date", "clementine", "guava", "dragonfruit",
            "nectarine", "sweet lime", "pawpaw", "salak", "blackberry",
            "currant", "cloudberry", "tamarind", "physalis", "jicama",
            "turnip", "parsnip", "rutabaga", "carrot", "beet",
            "celery", "kohlrabi", "broccoli", "cauliflower", "sprouts",
            "brussels sprouts", "cabbage", "green bean", "spinach", "swiss chard",
            "arugula", "endive", "escarole", "lettuce", "watercress",
            "pea", "bean", "lentil", "chickpea", "quinoa",
            "amaranth", "buckwheat", "rice", "oat", "barley",
            "wheat", "millet", "sorghum", "teff", "corn",
            "potato", "sweet potato", "yam", "cassava", "ginger",
            "turmeric", "garlic", "onion", "leek", "shallot",
            "chive", "scallion", "cilantro", "parsley", "basil",
            "oregano", "thyme", "rosemary", "sage", "peppermint",
            "spearmint", "tarragon", "fennel", "cumin", "coriander",
            "nutmeg", "cardamom", "clove", "anise", "vanilla",
            "cinnamon", "allspice", "mace", "mustard", "horseradish",
            "wasabi", "black pepper", "white pepper", "paprika", "chili",
            "cayenne", "jalapeño", "serrano", "habanero", "bell pepper",
            "banana pepper", "poblano", "chipotle", "green chili", "tomatillo",
            "cabbage", "eggplant", "zucchini", "bell pepper", "hot pepper",
            "sweet pepper", "tomato", "cucumber", "pumpkin", "pineapple",
            "kiwifruit", "nectarine", "pluot", "plumcot", "watermelon",
            "canteloupe", "honeydew", "starfruit", "mangosteen", "apricot",
            "pear", "grapefruit", "lime", "lemon", "orange",
            "blood orange", "tangerine", "satsuma", "clementine", "mandarin",
            "kumquat", "pummelo", "yuzu", "citron", "dragonfruit",
            "rambutan", "passionfruit", "jackfruit", "black sapote", "salak",
            "cempedak", "sapodilla", "longan", "soursop", "mamey",
            "chempedak", "white sapote", "fig", "cherimoya", "bilimbi",
            "rose apple", "carambola", "durian", "bignay", "cacao",
            "bilberry", "cloudberry", "gooseberry", "serviceberry", "raspberry",
            "blackberry", "blueberry", "youngberry", "boysenberry", "currant",
            "grape", "huckleberry", "cranberry", "marionberry", "dewberry",
            "chokecherry", "cherry", "date", "jackfruit", "jostaberry",
            "salmonberry", "wild berry", "bitter melon", "cucamelon", "cattley guava",
            "genip", "bush tomato", "beach strawberry", "strawberry guava", "sea grape",
            "winged bean", "winged bean", "pepino", "rambai", "salak",
            "dragon fruit", "soursop", "cherry", "loquat", "monk fruit",
            "seabuckthorn", "grumichama", "mamoncillo", "kanikou", "chikoo",
            "nashi pear", "jungle jalapeño", "duku", "mangaba"
        ];

if (typeof window !== 'undefined') {
    window.words = words;
}